server:
  port: 8085

spring:
  application:
    name: CustomerMS

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none  # Because table already exists
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:4567/eureka/
