server:
  port: 8090

spring:
  application:
    name: HealthMS

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:4567/eureka/

logging:
  level:
    org.springframework: INFO
    com.ofss: DEBUG
